### PR TITLE
v0.3

### LINKED ISSUE #32: Change contramap signature
To

```ts
contramap<A>(fa: HKT<A>[F]): <B>(f: (b: B) => A) => HKT<B>[F]
```

The current signature leads to unsafe code

```ts
type Predicate<A> = (a: A) => boolean

declare function contramap<A, B>(fa: Predicate<A>, f: (a: B) => A): Predicate<B>
declare function contramap2<A>(fa: Predicate<A>): <B>(f: (a: B) => A) => Predicate<B>

declare var o: Predicate<{ foo: string, bar: number }>

declare function f(): { foo: string }

contramap(o, f) // NO ERROR!
contramap2(o)(f) // ok, error: Property 'bar' is missing in type '{ foo: string; }'
```

### PR DESCRIPTION
**Pull request by gcanti**
Here's the list of breaking changes

- required typescript version: **2.3.3**
- Change contramap signature, closes #32
- Validation: remove deprecated functions
- Foldable/toArray
- Dictionary/fromFoldable
- Dictionary/toUnfoldable
- Profunctor/lmap
- Profunctor/rmap
- Unfoldable/replicate
- compositions renamed
  - `getFunctorComposition` -> `getStaticFunctorComposition`
  - `getApplicativeComposition` -> `getStaticApplicativeComposition`
  - `getFoldableComposition` -> `getStaticFoldableComposition`
  - `getTraversableComposition` -> `getStaticTraversableComposition`
- `OptionT`, `EitherT`, `ReaderT` refactoring
- drop `IxMonadT`, add `IxIO`
- drop `Trans` module
- `Free` refactoring
- drop `rxjs` dependency
- drop `lib-jsnext` folder

### CODE REVIEW

**Comment by sledorze** [comment]
@gcanti the sooner, the better, LGTM!

**Comment by gcanti** [comment]
@sledorze after three days of hacking full time there's still much to do, for instance

- add the `U = any, V = any` additional type parameters everywhere (easy, time consuming)
- figure out how to encode `Free` (hard)
- check the implementation against all my libs to make sure there are no regressions (easy, time consuming)

**Comment by gcanti** [comment]
> figure out how to encode Free (hard)

I think I have a candidate implementation (last commit) /cc @danielepolencic

**Comment by sledorze** [comment]
It look leaner from the diffs (on my phone)

**Comment by gcanti** [comment]
Ops.. I forgot to provide some context: why so many changes and why all this hacking? Two reasons

- (1) the "type inference pattern" is not applied everywhere
- (2) current type inference is pretty disappointing with higher kinds

Let's start from (2)

```ts
import { lift } from 'fp-ts/lib/Functor'
import * as either from 'fp-ts/lib/Either'

const double = (n: number) => n * 2

// Either has kind * -> * -> *

// eitherDouble :: <L>(fa: either.Either<L, number>) => either.Either<L, number>
const eitherDouble = lift(either, double)
```

Here `eitherDouble` has a good signature only because there is a specific overloading in `Functor.ts` (https://github.com/gcanti/fp-ts/blob/96dbdf7b3961ebcf72d5b93695b4d8215963aa87/src/Functor.ts#L12)

However overloadings, other than extremely noisy and ugly (`HKT2`, `HKT3` I'm looking at you..), fall short when you start composing types and producing even higher kinds

```ts
import { getFunctorComposition } from 'fp-ts/lib/Functor'

declare module 'fp-ts/lib/HKT' {
  interface HKT<A> {
    EitherEither: either.Either<any, either.Either<any, A>>
  }
  interface HKT2<A, B> {
    EitherEither: either.Either<any, either.Either<A, B>>
  }
  interface HKT3<A, B, C> {
    EitherEither: either.Either<A, either.Either<B, C>>
  }
}

const eitherEither = getFunctorComposition('EitherEither')(either, either)

// eitherEitherDouble :: <L>(fa: either.Either<any, either.Either<L, number>>) => either.Either<any, either.Either<L, number>>
const eitherEitherDouble = lift(eitherEither, double)
```

Note the `any` in the last signature. Another symptom is this issue https://github.com/gcanti/fp-ts/issues/95 by @OliverJAsh.

After some musings I had the following idea: what if we had just one `HKT` with multiple type parameters? (see here https://github.com/gcanti/fp-ts/issues/95#issuecomment-302774165)

With this change the trick used to fake higher kinded types could resolve multiple types

```ts
// using the code contained in this PR

import { getStaticFunctorComposition } from 'fp-ts/lib/Functor'

declare module 'fp-ts/lib/HKT' {
  interface HKT<A, U, V> {
    EitherEither: either.Either<V, either.Either<U, A>>
  }
}

const eitherEither = getStaticFunctorComposition('EitherEither')(either, either)

// eitherEitherDouble :: <U, V>(fa: either.Either<V, either.Either<U, number>>) => either.Either<V, either.Either<U, number>>
const eitherEitherDouble = lift(eitherEither, double)

// x :: either.Either<boolean, either.Either<string, number>>
const x = eitherEitherDouble(either.of<boolean, either.Either<string, number>>(either.of<string, number>(1)))
```

Amazing. And a bit scary.

As a consequence we get better type inference and all overloadings are gone.

There's a problem though: `OptionT`, `EitherT`, `ReaderT` and `Free` were implemented using a constraint on the first type parameter, for example here https://github.com/gcanti/fp-ts/blob/96dbdf7b3961ebcf72d5b93695b4d8215963aa87/src/OptionT.ts#L18 you can see

```ts
M extends HKTS
```

This is no more possible because in the new definition of `HKT`

```ts
export interface HKT<A, U = any, V = any> {}
```

`A`, `U` and `V` must be "free", i.e without constraints, otherwise TypeScript complains.

That should explain why I'm refactoring those 4 modules (using the "type inference pattern" (1)).

**Comment by gcanti** [comment]
Good news, TypeScript 2.3.3 is out

- now this project compiles (with 2.3.2 the build crashes)
- we can use default type parameters (extremely handy with the new `HKT` definition)

While developing I'm using `typescript@next` though, since the fix for https://github.com/gcanti/fp-ts/issues/49 is not included in 2.3.3

**Comment by gcanti** [comment]
> - add the U = any, V = any additional type parameters everywhere (easy, time consuming)
> - figure out how to encode Free (hard)
> - check the implementation against all my libs to make sure there are no regressions (easy, time consuming)

Done.

I put up a branch (`dev`) with the `lib` folder committed in, please give it a spin on your codebase / lib

```
npm i gcanti/fp-ts#dev
```

And here are the results for the last point:

- `elm-ts`: no changes required
- `io-ts`: no changes required
- `monocle-ts`: 1 change (`foldMap` signature)
- `parser-ts`: no changes required
- `types-io-ts`: no changes required
- `graphics-ts`: 3 changes
  - `Foldable.getFoldableComposition` -> `Foldable.getStaticFoldableComposition` renaming
  - `Foldable.toArray` signature
  - `Free.liftADT` -> `Free.liftF`

**Comment by sledorze** [comment]
@gcanti I'm experiencing again the GC issue with it..
I guess it is not related specifically to this lib but it may trigger some typescript errors cannot keep up with..

**Comment by OliverJAsh** [comment]
> @gcanti I'm experiencing again the GC issue with it..
> I guess it is not related specifically to this lib but it may trigger some typescript errors it cannot keep up with..

@sledorze I'm also experiencing the GC issue again. I posted a reproduction case here: https://github.com/Microsoft/TypeScript/issues/15443#issuecomment-302859678.

**Comment by sledorze** [comment]
thanks @OliverJAsh

**Comment by gcanti** [comment]
@sledorze are you using `typescript@2.3.3` ?

**Comment by OliverJAsh** [comment]
With https://github.com/OliverJAsh/ts-2.4-memory-issue/tree/2.4.0-dev.20170519, `tsc` runs out of memory on versions 2.3.3 and `@next` (`2.4.0-dev.20170519`).

**Comment by sledorze** [comment]
@gcanti I've tried with 2.3.3 and 2.4.dev (next)

**Comment by gcanti** [comment]
Note: the number of type parameters in `HKT` is **arbitrary**, now is 3 just because this number is compatible with all my current use cases. It's worth noting though that is extensible in any time and thanks to default type parameters the change will be backward compatible

**Pull request merged**
