### PR TITLE
Fr/migrate to curried

### PR DESCRIPTION
**Pull request by raveclassic**
This PR is a copy of #201 which tracks #200 

Migration list:
- [x] Alt 
- [x] Alternative
- [x] Applicative
  - [ ] getApplicativeComposition
- [x] Apply
  - [ ] ap
- [x] Array
  - ~fold~
  - ~slice~
- [x] Bifunctor
  - [ ] bimap (partial?)
- [x] Chain
  - [ ] chain
- [x] ChainRec
  - [ ] chainRec
  - [ ] tailRec
- [x] Comonad
- [x] Console
- [x] Const
- [x] Contravariant
  - [x] tests for Ops#lift
- [x] Either
  - [ ] fromPredicate
- [x] EitherT
- [x] Exception
- [x] Extend
  - [ ] extend
- [x] Field
- [x] Filterable
  - [ ] partitionMap
- [x] Foldable
  - [ ] reduce
  - [ ] getFoldableComposition
  - [ ] foldMap
  - [ ] foldr
  - [ ] intercalate
  - [ ] Ops#traverse_
  - [ ] Ops#sequence_
- [x] Free
- [x] Functor
  - [ ] map
  - [ ] Ops#flap
- [x] HKT
- [x] IO
- [x] Identity
- [x] IxIO
- [x] IxMonad
  - [ ] ichain
- [x] Monad
- [x] Monoid
- [x] Monoidal
- [x] NaturalTransformation
- [x] NonEmptyArray
- [x] Option
- [x] OptionT
- [x] Ord
- [x] Ordering
- [x] Pair
- [x] Plus
- [x] Profunctor
  - [ ] promap
- [x] Random
- [x] Reader
- [x] ReaderT
- [x] Ring
- [x] Semigroup
- [x] Semigroupoid
- [x] Semiring
- [x] Setoid
- [x] State
- [x] StateT
- [x] Store
- [x] StrMap
  - [ ] mapWithKey
- [x] Task
- [x] These
  - [ ] concat
- [x] Trace
  - ~trace~
- [x] Traversable
  - [ ] traverse
  - [ ] sequence
- [x] Tuple
  - [ ] getSetoid 
  - [ ] getOrd
  - [ ] getSemigroup
- [x] Unfoldable
  - [ ] replicateA
  - [ ] singleton
- [x] Validation
  - [ ] fromPredicate 
- [x] Witherable
  - [ ] Ops#wither
  - [ ] Ops#wilted
  - [ ] Ops#withered
- [x] Writer
- [ ] function
  - ~tuple~
  - [ ] or
  - [ ] and
  - [ ] on

### CODE REVIEW

**Comment by gcanti** [comment]
@raveclassic With the current order of arguments I think we should keep Functor.map uncurried otherwise type inference will suffer

```ts
export interface Functor<F> {
  readonly URI: F
  map: <A, B>(f: (a: A) => B, fa: HKT<F, A>) => HKT<F, B>
}
```

the `fa` argument here helps ts to infer the type `A`, otherwise you have to always add type annotations to the argument `f`.

If you want to curry `map`, we should swap the arguments (as in Scala)

```ts
export interface Functor<F> {
  readonly URI: F
  map: <A>(fa: HKT<F, A>) => <B>(f: (a: A) => B) => HKT<F, B>
}
```

**Comment by gcanti** [comment]
The problem is that in a real world scenario you likely want to apply the `f` argument. Now if we swap the arguments, you can't still do that, hence we end up with a breaking change with no apparent gain

**Comment by raveclassic** [comment]
@gcanti Agree. What about leaving such cases as is and currying everything else where possible?

**Comment by gcanti** [comment]
Yep, we can carry on for now and come back to this topic in a second phase

**Comment by raveclassic** [comment]
@gcanti Ok I'll try to mark all problematic places

**Comment by gcanti** [comment]
Note (to myself): do not curry `function.tuple` :)

**Comment by raveclassic** [comment]
> Note (to myself): do not curry function.tuple :)

Just noticed there are actually two `tuple` functions - uncurried in `function.ts` and curried in `Monoidal.ts` :)

**Comment by gcanti** [comment]
The `function.tuple` is an handy helper because ts infers `[1, 'a']` as `(string | number)[]
` instead of `[number, string]` (I should add a comment)

p.s. working on the `Array` module

**Comment by gcanti** [comment]
@raveclassic Working on Chain, ChainRec, Either, EitherT

**Comment by gcanti** [comment]
Working on Exception, Extend, Filterable, Foldable, Functor

**Comment by raveclassic** [comment]
@gcanti Noticed a cast `eq(alt(none as Option<number>)(some(2)), some(2))`. We need to add some overloads to Option's `alt`:
```typescript
// overload here to support 'none' as first argument
export function alt(fx: Option<never>): <A>(fy: Option<A>) => Option<A>
export function alt<A>(fx: Option<A>): (fy: Option<A>) => Option<A>
export function alt<A>(fx: Option<A>): (fy: Option<A>) => Option<A> {
  return fy => fx.alt(fy)
}
```

Fixed it here

**Comment by gcanti** [comment]
Ah.. I thought they were vestigial. Maybe there's no need for special casing though, usually you get an `Option<A>` rather than a `None`:

```ts
import { alt, none, some, Option } from '../src/Option'

function f(): Option<number> {
  return none
}

alt(f())(some(1))
// or even
eq(alt<number>(none)(some(2)), some(2))
```

**Comment by raveclassic** [comment]
Ok I think we're done here!

**Comment by gcanti** [comment]
@raveclassic I left the Trace module uncurried intentionally, that's because it's supposed to be a quick and dirty way to debug the code, what's your opinion?

**Comment by raveclassic** [comment]
Ok I reverted that change

**Comment by gcanti** [comment]
For what concerns the left bits, this is my proposal

Legend:

- TCR: type constraint rule: all type constraints are grouped together
- TI: currying will cause bad type inference
- TU: is not curried because of the typical usage

Functions

- `Applicative.getApplicativeComposition` Won't fix: TCR
- `Apply.ap` Won't fix: TI
- `Bifunctor.bimap` Won't fix: TU
- `Chain.chain` Won't fix: TI
- `ChainRec.chainRec` Won't fix: TI
- `ChainRec.tailRec` Won't fix: TI
- `Either.fromPredicate` Won't fix: TU
- `Extend.extend` Won't fix: TI
- `Filterable.partitionMap` Won't fix: TI
- `Foldable.reduce` Won't fix: TI
- `Foldable.getFoldableComposition` Won't fix: TCR
- `Foldable.foldMap` Won't fix: TCR
- `Foldable.foldr` **will fix**
- `Foldable.intercalate` Won't fix: TCR
- `Foldable.traverse_` Won't fix: TCR
- `Foldable.sequence_` Won't fix: TCR
- `Functor.map` Won't fix: TI
- `Functor.flap` *is already curried*
- `IxMonad.ichain` Won't fix: TI
- `Profunctor.promap` **will fix** (only the `fbc` argument)
- `StrMap.mapWithKey` Won't fix: TU
- `These.concat` Won't fix: TCR
- `Traversable.traverse` Won't fix: TI
- `Traversable.sequence` Won't fix: TCR
- `Tuple.getSetoid` Won't fix: TCR
- `Tuple.getOrd` Won't fix: TCR
- `Tuple.getSemigroup` Won't fix: TCR
- `Unfoldable.replicateA` Won't fix: TCR
- `Unfoldable.singleton` **will fix**
- `Validation.fromPredicate` Won't fix: TU
- `Witherable.wither` Won't fix: TCR + TI
- `Witherable.wilted` Won't fix: TCR
- `Witherable.withered` Won't fix: TCR

Let me know if you agree or want to change something

**Pull request merged**
