### PR TITLE
Task: implement neglect function

### PR DESCRIPTION
**Pull request by cyberixae**
This PR adds `neglect` function that turns a Task into a detached background job.

### CODE REVIEW

**Comment by gcanti** [comment]
@cyberixae not sure I'm following, `neglect` is just the `identity` function

```ts
export const neglect: (t: Task<unknown>) => IO<void> = identity
```

**Comment by cyberixae** [comment]
> @cyberixae not sure I'm following, `neglect` is just the `identity` function
> 
> ```ts
> export const neglect: (t: Task<unknown>) => IO<void> = identity
> ```

On type level they are the same but if you `console.log` the `void` returned by my `neglect` implementation it actually returns `undefined` since it discards the Promise instead of returning it. If I replace the implementation with `identity` the void value will be `Promise<something>` at run time, which I find to be a bit confusing.

**Comment by gcanti** [comment]
What I meant is that I don't see how `neglect` would be useful in practice since is just the identity function.

Also, keep in mind that in TypeScript `void` doesn't mean that a function returns `undefined` at runtime

```ts
const f: (s: string) => void = (s) => s.length // no error
```

Thanks for this PR but I'm afraid I can't accept it

**Comment by cyberixae** [comment]
Wait, what?! I encountered the problem because I was using the `function` keyword instead of double arrow. See the attached screenshot.

vscerr

**Comment by cyberixae** [comment]
Anyway, thanks for reviewing the PR. I never noticed before that void behaved that way with double arrow.

**Pull request closed without merging**
