### PR TITLE
Flip the arguments of a curried function

### PR DESCRIPTION
**Pull request by thewilkybarkid**
I've been using this `flipC` in combination with `Reader`'s `local` to hide implementation details, based on https://andywhite.xyz/posts/2021-01-28-rte-react/#service-layers-and-implementation-hiding (e.g. https://github.com/PREreview/prereview.org/blob/35278c267c541586f7ca505b9bd9f5a634ec3e93/src/app.ts#L81).

This function dates back to @jskeate's suggestion in https://functionalprogramming.slack.com/archives/CPKPCAGP4/p1655736152988389?thread_ts=1655730853.886439&cid=CPKPCAGP4.

Another option could be to overload `flip`, though I've not tried that.

### CODE REVIEW

**Comment by samhh** [comment]
This is one of the few cases where I used a conflicting name in [fp-ts-std](https://samhh.github.io/fp-ts-std/modules/Function.ts.html#flip) - I don't think uncurried functions should get the proper name `flip` in a FP library.

Could we perhaps target a breaking change in 3.0 that rewrites `flip` to the curried version in this PR (and optionally renames uncurried `flip` to something else)? v3 includes [other curry-friendly breaking changes](https://github.com/gcanti/fp-ts/issues/1216).

**Comment by thewilkybarkid** [comment]
I've pushed 20268fc39144c5fc6fdca81bf1b9adfcf1d0c507 based on @samhh's suggestion to replace the existing `flip`: I've deprecated two arguments in favour of a new function `flipArgs`.

Not sure which approach you'd rather take @gcanti.

**Comment by gcanti** [comment]
> Could we perhaps target a breaking change in 3.0 that rewrites `flip` to the curried version in this PR

I agree, I would:

- add the `export function flip<A, B, C>(f: (a: A) => (b: B) => C): (b: B) => (a: A) => C` overloading to the existing `flip` function
- deprecate the existing `export function flip<A, B, C>(f: (a: A, b: B) => C): (b: B, a: A) => C` signature
- keep the `@since 2.0.0` tag
- do not export a `flipArgs` function

**Comment by thewilkybarkid** [comment]
@gcanti Should be sorted now.

**Review by gcanti — APPROVED** [review]

**Pull request merged**
