### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by DenisFrezzato**

### CODE REVIEW

**Comment by gcanti** [comment]
@DenisFrezzato that's not a typo, it means that you can prove to the type checker that the array is actually not empty

**Comment by DenisFrezzato** [comment]
I just fixed the word, I didn't delete it.

**Comment by gcanti** [comment]
What I mean is that there's nothing to fix, "provably" (= "in way that can be shown as true") is already the right word for the constraint `Array<A> & { 0: A }`

**Comment by DenisFrezzato** [comment]
Oh, ok, sorry then :)

**Pull request closed without merging**
