### PR TITLE
Docs: remove all non technical documentation

### PR DESCRIPTION
**Pull request by gcanti**

### CODE REVIEW

**Comment by ford04** [comment]
What happend to the Recipes section? Especially [Async tasks](https://github.com/gcanti/fp-ts/blob/5684ae1919044267d2b5a706800fd528bf6afc51/docs/recipes/async.md) was my No.1 rescue page, I often consulted 🙂. Thanks in advance!

 (or am I just missing it on the current page)

**Comment by grossbart** [comment]
I migrated the recipes to their own repository just now so they are available again. I'll submit a PR to this repo soon with a link to those recipes.

Mind you, there are still broken links in there and the examples need highlighting (or, preferrably, a REPL). But it's a start :)

https://grossbart.github.io/fp-ts-recipes/

**Comment by newswim** [comment]
@grossbart would you consider also adding the rambda table?

https://github.com/gcanti/fp-ts/blob/1.x/docs/recipes/ramda.md

**Comment by gcanti** [comment]
@newswim that was for `fp-ts@1.x`, for `fp-ts@2.x` there's [fp-ts-ramda](https://github.com/giogonzo/fp-ts-ramda)

**Pull request merged**
