### PR TITLE
Added Option.toArray

### PR DESCRIPTION
**Pull request by psilospore**
In Scala I can do `Option(1).toList` this would do something similar

### CODE REVIEW

**Comment by gcanti** [comment]
@psilospore I'd rather (re)add `toArray` to `Foldable`

(adpated from https://github.com/gcanti/fp-ts/blob/1.x/src/Foldable2v.ts)

```ts
import { Foldable, Foldable1, Foldable2, Foldable2C, Foldable3, Foldable3C, Foldable4 } from 'fp-ts/lib/Foldable'
import { HKT, Kind, Kind2, Kind3, Kind4, URIS, URIS2, URIS3, URIS4 } from 'fp-ts/lib/HKT'

/**
 * Transforms a foldable into an array
 *
 * @example
 * import { toArray } from 'fp-ts/lib/Foldable'
 * import { tree, make } from 'fp-ts/lib/Tree'
 *
 * const t = make(1, [make(2, []), make(3, []), make(4, [])])
 * assert.deepStrictEqual(toArray(tree)(t), [1, 2, 3, 4])
 *
 * @since 2.6.0
 */
export function toArray<F extends URIS4>(F: Foldable4<F>): <S, R, E, A>(fa: Kind4<F, S, R, E, A>) => Array<A>
export function toArray<F extends URIS3>(F: Foldable3<F>): <R, E, A>(fa: Kind3<F, R, E, A>) => Array<A>
export function toArray<F extends URIS3, E>(F: Foldable3C<F, E>): <R, A>(fa: Kind3<F, R, E, A>) => Array<A>
export function toArray<F extends URIS2>(F: Foldable2<F>): <E, A>(fa: Kind2<F, E, A>) => Array<A>
export function toArray<F extends URIS2, E>(F: Foldable2C<F, E>): <A>(fa: Kind2<F, E, A>) => Array<A>
export function toArray<F extends URIS>(F: Foldable1<F>): <A>(fa: Kind<F, A>) => Array<A>
export function toArray<F>(F: Foldable<F>): <A>(fa: HKT<F, A>) => Array<A>
export function toArray<F>(F: Foldable<F>): <A>(fa: HKT<F, A>) => Array<A> {
  return <A>(fa: HKT<F, A>) =>
    F.reduce<A, Array<A>>(fa, [], (acc, a) => {
      acc.push(a)
      return acc
    })
}

// --------------------------------
// examples
// --------------------------------

import { tree, make } from 'fp-ts/lib/Tree'
import { option, some, none } from 'fp-ts/lib/Option'
import * as assert from 'assert'

// Option
const optionToArray = toArray(option)
assert.deepStrictEqual(optionToArray(some(1)), [1])
assert.deepStrictEqual(optionToArray(none), [])

// Tree
const treeToArray = toArray(tree)
assert.deepStrictEqual(treeToArray(make(1, [make(2, []), make(3, []), make(4, [])])), [1, 2, 3, 4])
```

**Comment by DenisFrezzato** [comment]
>I'd rather (re)add toArray to Foldable

+1 to this, seams reasonable to have it.

**Comment by psilospore** [comment]
That seems better thanks!

**Comment by gcanti** [comment]
Closing in favour of https://github.com/gcanti/fp-ts/pull/1272

**Pull request closed without merging**
