### PR TITLE
Documentation: add blog links, closes #1049

### LINKED ISSUE #1049: Add `Reader` usage example
## 📖 Documentation

It would be great to have some minimal example usage of `Reader` monad. As far as I understand, it's purpose is to avoid threading arguments through multiple functions in order only to get them where they belong (at the bottom of calls). It would be nice if there's an example of how to refactor e.g. such a code using `Reader`:
```ts
interface Config {
  // ...
  logLevel: number;
  // ...
}

function foo(config: Config) {
  // ...
  return bar(config)  // `bar` doesn't really needs it, it only passes it further
}

function bar(config: Config) {
  // ...
  baz(config)
  // ...
}

function baz(config: Config) {
  // ...
  if(config.logLevel > 5) writeToLogFile("Error occured in baz")
  // ...
}
```

### PR DESCRIPTION
**Pull request by gcanti**

### CODE REVIEW

**Comment by gkamperis** [comment]
Wouldn't it be better if you hosted the post in the docs and referenced that?

Actually the whole series... 
They serve as great documentation. 

Git location is guaranteed. Dev.to might not be there or the link might change....

**Comment by gcanti** [comment]
> Git location is guaranteed. Dev.to might not be there or the link might change....

You are right, I'll work on this asap

**Comment by gcanti** [comment]
@gkamperis done, there are two new sections, "Getting started", and "Functional design" https://gcanti.github.io/fp-ts/getting-started/

**Comment by gkamperis** [comment]
@gcanti looks fantastic! these articles really helped me out and I keep reading them again and again! Hopefully it will help more people too.

**Pull request merged**
