### PR TITLE
optimize Filterable instances (Array, StrMap)

### PR DESCRIPTION
**Pull request by gcanti**

### CODE REVIEW

**Comment by gcanti** [comment]
@raveclassic working on a PR for `Either`

**Comment by raveclassic** [comment]
@gcanti Oups I've just pushed all updated ADTs

**Comment by gcanti** [comment]
@raveclassic no problem, I just wanted to help you out ;)

**Comment by raveclassic** [comment]
@gcanti Thanks a lot anyway :)

**Pull request closed without merging**
