### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by gcanti**
@raveclassic @sledorze

Changelog: see commits

Try: `npm i gcanti/fp-ts#next`

### CODE REVIEW

**Comment by gcanti** [comment]
@raveclassic @sledorze (and everybody else) 

Next steps? What can I do to help you testing this version, maybe in a real scenario?

One option would be

- publish this version in the `@next` channel
- publish a `io-ts` version pointing to ^ in the `@next` channel (just verified: no breaking changes)
- maybe the same thing for `monocle-ts` (?) (just verified: no breaking changes)

Are there other libraries around fp-ts that are you using?

**Comment by raveclassic** [comment]
@gcanti I'm using `typelevel-ts` but it seems like it shouldn't be affected. Unfortunately our project is being stabilized now before its release so I can't update fp-ts to test it on large codebase.

**Comment by sledorze** [comment]
@gcanti we're using `monocle-ts` too.
I'm a few days before a 1 week holidays so will *really* try to give it a go but no promises.

**Comment by gcanti** [comment]
Ok, published on npm

- `fp-ts@next` (`fp-ts@1.0.0-rc`)
- `io-ts@next` (`io-ts@0.9.8-rc`)
- `monocle-ts@next` (`monocle-ts@0.5.3-rc`)
- `io-ts-types@next` (`io-ts-types@0.2.5-rc`)
- `newtype-ts@next` (`newtype-ts@0.1.3-rc`)

Except fp-ts, the other packages should **NOT** have API breaking changes

**Comment by gcanti** [comment]
Those releases are mainly for early feedback, I'm waiting to update the documentation when things settle down and we are satisfied by the result. 

Namely

- changelog (will be huge)
- docs/HKT.md

Conversely `examples` and `exercises` should be up to date

**Comment by sledorze** [comment]
@gcanti Here I will consolidate the issues I encounter:

Problem with Either predicates.

Previous version:
```typescript
        import { either } from 'fp-ts'
...
        arrayOfEithers
        .filter(either.isRight) // predicate
        .map(x => ...) // x is Right<..> :)
```

New version:
```typescript
        arrayOfEithers
        .filter(x => x.isRight()) // predicate refines x 
        .map(x => ...) // x is Either<..> :(
```
We're missing that kind of support:

```typescript
export const isRight = <A, B>(x: either.Either<A, B>): x is either.Right<A, B> =>
  x.isRight()
```

**Comment by gcanti** [comment]
@sledorze I would argue that using `Right` as a type is wrong: `Right` is a constructor not a type (well in TypeScript _is_ also a type because of the implementation and because I'm forced to export `Left` and `Right` by TypeScript itself but should be considered as an implementation detail)

In PureScript for example you can't use `Right` as a type

```purescript
data Either l r = Left l | Right r

x :: Right String -- doesn't compile
x = Right "foo"

x :: Either Number String -- ok
x = Right "foo"
```

p.s.

Also in your particular case there's [`Array.rights`](https://github.com/gcanti/fp-ts/blob/da8091ef4c2f7908e71149ed4ad956fdc6f613cf/src/Array.ts#L510)

**Comment by sledorze** [comment]
@gcanti this is not on array but on (rxjs) observables the use case is not easy without those refinements.
The only solution is to recreate that top level predicate (idiomatic) OR to define another Observable combinator (which a end user would see as the least solution).
Also `Right`, as implemented, is a type in `typescript` and its usage is very useful and idiomatic; why restricting it to the possibilities of Purescript.
That's why I think we should (re)add it (based on a real world code base).

**Comment by sledorze** [comment]
@gcanti 
Note on the order of params.
I see that Functor and Chain params are now inverted like so:
```
chain: <A, B>(fa: HKT<F, A>, f: (a: A) => HKT<F, B>) => HKT<F, B>;
map: <A, B>(fa: HKT<F, A>, f: (a: A) => B) => HKT<F, B>;
```

But on Apply that's not the case:
```
ap: <A, B>(fab: HKT<F, (a: A) => B>, fa: HKT<F, A>) => HKT<F, B>;
```
is it deliberate? (if so, why?)

**Comment by gcanti** [comment]
> why restricting it to the possibilities of Purescript

PureScript is my reference when it comes to establish what's good and what's bad, in particular with respect to functional programming.

However if there is consensus I'm ok to re-add those custom guards because

- clearly you find them useful
- one less breaking change

**Comment by sledorze** [comment]
Ok anyway i m adding the missing bits into a file so that we can review it later.

**Comment by gcanti** [comment]
> is it deliberate? (if so, why?)

Based on my early experiments there's no gain in terms of type inference / suggestions by swapping the `Apply` arguments. I'll investgate further though

**Comment by sledorze** [comment]
@gcanti i was specifically thinking about approachability by homogeneity (if not, wondering what s the default/preferred behavior)

**Comment by sledorze** [comment]
@gcanti I find we lack meaningful definition for Ordering (I miss LT, EQ, GT) even if they map to -1, 0, 1 in the end.

**Comment by sledorze** [comment]
@gcanti Ok so I've ported our code base on the new version.

Notable:

- A lot of foldL usage (63).

- new order of args leads to better inference AND looks better also with prettier; often we can see everything in the first line as the biggest param (the function) is the last one.

- Took me a bit of time to understand there was new Monad1, Monad2, etc.. while porting some monadTransformers.

- miss the isRight / isSome a lot in the front-end side (observables) by our frontEnd guy; for that kind of two stage usages: ```opt$.filter(isSome).map(x => x.value)```.

- no array.concat; I'm using array.flatten, I don't know if it's better or not performance wise.

- Less type params to write explicitly.

Overall, I would consider this version as ready for usage.

**Comment by sledorze** [comment]
@gcanti oh I forgot to say that io-ts-types are not referencing the new libs explicitly.

**Comment by gcanti** [comment]
@sledorze great feedback, thanks

> miss the isRight / isSome

ok I'm going to re-add them (*)

> no array.concat

you can import `concat` either from the `function` module or calling `Array.getSemigroup()`

> io-ts-types are not referencing the new libs explicitly

My plan would be

- release `fp-ts@1.0.0` (after (*))
- merge https://github.com/gcanti/io-ts/pull/112 and release `io-ts@1.0.0`
- update all remaining libraries (inluded a cleaned up `io-ts-types`)

**Comment by gcanti** [comment]
UPDATE

I'm working on a bunch of PRs, the goal would be to coordinate all releases in one shot. Here's the dependencies

```
fp-ts (v1.0.0) -- io-ts (v1.0.0)
              \-- monocle-ts (v1.0.0)
                                    \-- newtype-ts (v0.2.0)
                                                           \-- io-ts-types (v0.3.0)
```

You can install the current candidates by running

- `npm i gcanti/fp-ts#next` 
- `npm i gcanti/io-ts#next` (related PR [here](https://github.com/gcanti/io-ts/pull/112))
- `npm i gcanti/monocle-ts#next` (related PR [here](https://github.com/gcanti/monocle-ts/pull/41))
- `npm i gcanti/newtype-ts#next` (related PR [here](https://github.com/gcanti/newtype-ts/pull/6))
- `npm i gcanti/io-ts-types#next` (related PR [here](https://github.com/gcanti/io-ts-types/pull/17))

(for these kind of tests / quick feedback installing from github looks more practical than publishing on npm)

Let me know if you hit any issue

**Comment by sledorze** [comment]
Ok, got no issue so far (but was not able to test with your latest changes - aka type guards - as they've not been published yet).

**Pull request merged**
