### PR TITLE
Add scan left/right functions

### PR DESCRIPTION
**Pull request by PaNaVTEC**
Hi, 

I've observed that in haskell/scala they have a scan function which allows to do a fold carrying intermediate steps and I've translated the haskell implementation to TS.

http://hackage.haskell.org/package/base-4.10.1.0/docs/src/GHC.List.html#scanl
https://github.com/scala/collection-strawman/blob/57340b9fa6732a0bae37845f16dfb272fbb2173a/collections/src/main/scala/strawman/collection/immutable/LazyList.scala#L271

### CODE REVIEW

**Comment by sledorze** [comment]
I think we should warn for stack safety.

**Comment by PaNaVTEC** [comment]
@sledorze Thanks for your comment, you are right. 
What about this implementation: 

```export const scan = <A, B>(f: ((b: B, a: A) => B), b: B, as: Array<A>): Array<B> => {
  const l = as.length
  let r = [b]
  for (let i = 0; i < l; i++) {
    r.push(f(r[i], as[i]))
  }
  return r
}
```
It does the same and it is iterative, so we don't have to worry about that

**Comment by sledorze** [comment]
@PaNaVTEC thanks!
Sorry for being picky but performance wise, it would be nice to follow that preallocation scheme (which was backed by actual measurement):
https://github.com/gcanti/fp-ts/blob/master/src/Array.ts#L45-L52

I think we're close to it :)

**Comment by PaNaVTEC** [comment]
@sledorze true again, I didn't even noticed. Thanks for your review :)

**Comment by sledorze** [comment]
@PaNaVTEC I'm sorry, shouldn't it be more like:

```typescript
export const scan = <A, B>(f: ((b: B, a: A) => B), b: B, as: Array<A>): Array<B> => {
  const l = as.length
  let r = new Array(l+1)
  r[0] = b;
  for (let i = 0; i < l; i++) {
    r[i+1] = f(r[i], as[i]);
  }
  return r
}
```

**Comment by sledorze** [comment]
@PaNaVTEC also I looks to briefly but to fit with the rest of the lib you may reverse the params.

**Comment by gcanti** [comment]
About the name, there's `scanr` too, so maybe `scanl` (or `scanLeft`)?

> you may reverse the params

Yes, type inference for `f` will be much better with the following signature

```ts
<A, B>(as: Array<A>, b: B, f: (b: B, a: A) => B): Array<B>
```

**Comment by sledorze** [comment]
@gcanti Oh yes, `scan` may be ambiguous `scanl`.

**Comment by PaNaVTEC** [comment]
@gcanti @sledorze I didn't want to add that l in the name because I've seen that you guys have a `reduce` function but there is not `reduceRight` and `fold` has a `foldL` but that L means Lazy, I can add if it is clearer tho

**Comment by sledorze** [comment]
@PaNaVTEC good point, @gcanti let's discuss it!

**Comment by sledorze** [comment]
One possibility is to name the combinators 'xxxLeft' and 'xxxRight' and keep an extra 'L' for their lazy variant.
Have a default alias without 'Left' or 'Rigth' but make that clear in the comment.

**Comment by gcanti** [comment]
In `Foldable` there's 

- `foldl`, however is called `reduce`, vestiges of the past (fantasy-land compatibility)
- and `foldr`

I'd go for `scanl` or `scanLeft` (but no aliases)

**Comment by gcanti** [comment]
> the intersection of current input goes in favour of scanLeft

ok for `scanLeft`

@PaNaVTEC there's no need to update the documentation, I'll handle that before releasing next version, thanks

**Comment by PaNaVTEC** [comment]
Thank you for your help guys. I've added `scanRight` and renamed the other to `scanLeft`

**Comment by sledorze** [comment]
@PaNaVTEC that's great!

**Comment by PaNaVTEC** [comment]
Since @gcanti said there is not need to update the documentation, is there anything else I can do to merge this?

**Comment by gcanti** [comment]
Thanks @PaNaVTEC

**Pull request merged**
