### PR TITLE
Performance improvement for Task

### PR DESCRIPTION
**Pull request by sahincapiec**
I removed some unnecessary promises creations. Thus reducing tick's calls and increasing the performance.

### CODE REVIEW

**Comment by xuanduc987** [comment]
It was intentional https://github.com/gcanti/fp-ts/pull/1591

**Comment by sahincapiec** [comment]
Yes. I understand, but it's still working with my changes. It's stack-safe but faster. There were many redundant and unnecessary promise creations.

**Comment by xuanduc987** [comment]
Only `chain`, which is not touched by this PR is stack-safe.
You can see the stack blow up with
```ts
let pipeline = T.of(0)
for (let i = 0; i < 55000; i++) {
  pipeline = pipe(
    pipeline,
    T.map(n => n + 1)
  )
}
await pipeline()

```

**Comment by enricopolanski** [comment]
Just a small hint imho: when opening PRs that contain performance changes please provide the numbers in the PR.

**Comment by pbadenski** [comment]
Could someone explain what happened that this PR was closed? I haven't quite understood the conversation. I've been looking at #1591 and wondering about performance impact in promise heavy environment (my preliminary micro-benchmarks show stack-safe impl. to be 2 x slower).

**Pull request closed without merging**
