### PR TITLE
Setup Denoify for deno compatibility

### PR DESCRIPTION
**Pull request by garronej**
Hi @gcanti,  
I am the author of [denoify](https://github.com/garronej/denoify).  
I saw on Reddit someone saying it was a shame `fp-ts` wasn't available on [deno.land/x](https://deno.land/x) so I took the initiative to set up Denoify on the repo.  
If you merge you'll be able to be listed on [deno.land/x](https://deno.land/x).

First you'll have to click on "Publish a module"

image

I suggest "fp_ts" since "-" aren’t allowed.  

image

image

After that you'll have to set up Webhooks.  

[This CI workflow](https://github.com/gcanti/fp-ts/blob/4021c299097a722d3c6c7ff162a14ad88144234c/.github/workflows/main.yml#L31-L94) will detect each time the `package.json` version has been updated and create a new tag with the version number that points to a new `latest` branch that contains a `deno_dist/` directory (alongside all the other files).

Please be careful before merging. You might want to adapt the workflow to better integrate with your current way of releasing. If you want an idea of what would be the final result, you can have a look at [tsafe](https://github.com/garronej/tsafe).  
  
I am happy to help if you need further assistance. (Assuming you’re interested in officially supporting Deno 😄)

Best regards,

### CODE REVIEW

**Comment by garronej** [comment]
It's completed yet, I will undraft once I'd have fixed the remaining bugs on the [denoify](https://github.com/garronej/denoify) side.

**Comment by PerArneng** [comment]
This would be so awesome. fp-ts is one of the most important libraries for me when using TypeScript. To be able to use it on deno would be really great!  Thanks!

**Comment by gcanti** [comment]
Thank you @garronej but I'm not interested in officially supporting Deno

**Comment by garronej** [comment]
Ok, your project your rules.  
It's a shame because with you star count you would have been instantaneously propelled at the front page of deno.land/x and there is almost nothing else for you to do to get there but to press merge.
I guess I will just publish from my fork but it will not be kept up to date automatically and it will not be as visible.

**Comment by garronej** [comment]
@PerArneng @GabeAtWork @clord @mushegha @Industrial @remexre [It's published](https://deno.land/x/fp_ts) from my fork if you are interested.

**Comment by Industrial** [comment]
@garronej Hi!

I have tried using `import * as O from "https://deno.land/x/fp_ts@v2.11.4/Option.ts";`

This gives me

```
error: TS2344 [ERROR]: Type '"Predicate"' does not satisfy the constraint 'keyof URItoKind<any>'.
const contramap_: Contravariant1<URI>['contramap'] = (predicate, f) => pipe(predicate, contramap(f))
                                 ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Predicate.ts:24:34

TS2344 [ERROR]: Type '"Predicate"' does not satisfy the constraint 'keyof URItoKind<any>'.
export const Contravariant: Contravariant1<URI> = {
                                           ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Predicate.ts:92:44

TS2344 [ERROR]: Type '"Separated"' does not satisfy the constraint '"Either"'.
const _map: Functor2<URI>['map'] = (fa, f) => pipe(fa, map(f))
                     ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Separated.ts:47:22

TS2344 [ERROR]: Type '"Separated"' does not satisfy the constraint '"Either"'.
const _mapLeft: Bifunctor2<URI>['mapLeft'] = (fa, f) => pipe(fa, mapLeft(f))
                           ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Separated.ts:48:28

TS2344 [ERROR]: Type '"Separated"' does not satisfy the constraint '"Either"'.
const _bimap: Bifunctor2<URI>['bimap'] = (fa, g, f) => pipe(fa, bimap(g, f))
                         ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Separated.ts:49:26

TS2344 [ERROR]: Type '"Separated"' does not satisfy the constraint '"Either"'.
export const Bifunctor: Bifunctor2<URI> = {
                                   ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Separated.ts:109:36

TS2344 [ERROR]: Type '"Separated"' does not satisfy the constraint '"Either"'.
export const Functor: Functor2<URI> = {
                               ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Separated.ts:119:32

TS2344 [ERROR]: Type '"Eq"' does not satisfy the constraint 'keyof URItoKind<any>'.
export const Contravariant: Contravariant1<URI> = {
                                           ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Eq.ts:154:44

TS2344 [ERROR]: Type '"Eq"' does not satisfy the constraint 'keyof URItoKind<any>'.
export const eq: Contravariant1<URI> = Contravariant
                                ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Eq.ts:198:33

TS2344 [ERROR]: Type '"Ord"' does not satisfy the constraint 'keyof URItoKind<any>'.
export const Contravariant: Contravariant1<URI> = {
                                           ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Ord.ts:222:44

TS2344 [ERROR]: Type '"Ord"' does not satisfy the constraint 'keyof URItoKind<any>'.
export const ord: Contravariant1<URI> = Contravariant
                                 ~~~
    at https://deno.land/x/fp_ts@v2.11.4/Ord.ts:352:34
```

It seems like the code is not directly usable and needs some changes to work with Deno. Maybe I can be of help here?

The errors seem to stem from one type `URIToKind`.

I can not open issues at https://github.com/garronej/fp-ts. Are you on discord?

**Comment by garronej** [comment]
@Industrial,  
Sorry about that. I didn't test in depth because I wasn't sure it was going to be used.  
The code is already transformed to some extend by [Denoify](https://github.com/garrone/denoify). I think the error is related with `declare module` and how denoify paches it.  
If you find the source of the error and what exactly need to be changed for the Deno code to work I will happily update Denoify.  
Maybe I should setup de test to run on Deno as well. I didn't do it because I wanted to keep the diff as small as possible in the hope that it be merged.   
Anyway you can reach me on [Discord](https://discord.gg/bXa2DzDE) and yes I think it's better to continue the discution on my fork unfortunately. 

Regards

**Comment by MichaelHirn** [comment]
@garronej @Industrial I created a working [fp-ts port for Deno](https://github.com/MichaelHirn/fp-ts)

@garronej 99% of the typescript errors are due to `HKT.ts` types as Industrial pointed out. Not sure what can be learned for Denoify from that but have a look at the [fixtures/HKT.ts](https://github.com/MichaelHirn/fp-ts/master/fixtures/HKT.ts) to see what fixed it. The other 1% are small type inference issues (unknown or any) - again not sure if Denoify can auto solve that.

**Pull request closed without merging**
