### PR TITLE
Add `toUndefined` to the Option type

### PR DESCRIPTION
**Pull request by vegansk**
as it discussed here: #225

### CODE REVIEW

**Comment by gcanti** [comment]
@vegansk btw does fp-ts play well with React?

**Comment by raveclassic** [comment]
@gcanti Perfectly :)

**Comment by vegansk** [comment]
@gcanti , yep. The only really missing thing is the do notation, but how we can have it without ts support in sweetjs, I don't know :-)

**Comment by raveclassic** [comment]
@vegansk There [is a way](https://github.com/fluture-js/Fluture#do) but with a loss of type safety, because TS type system doesn't play well with generators. Actually is does not at all =(

**Comment by vegansk** [comment]
So let's wait when macros will arrived. I already have an experience of adding do notation to the language that doesn't support it using macros :-) https://github.com/vegansk/nimfp/blob/master/tests/fp/test_forcomp.nim#L48

**Pull request merged**
