### PR TITLE
NonEmptyArray enhancement (fixes #627)

### LINKED ISSUE #627: Add some more NonEmptyArray functions
Implement `index`, `findFirst`, `findIndex`, `insertAt`, `updateAt`, `filter` for NonEmptyArray

I may issue a PR.

@gcanti Ok with all of those?

### PR DESCRIPTION
**Pull request by sledorze**
add index, findFirst, findLast, findIndex, findLastIndex, insertAt, updateAt, filter to nonEmptyArray and homogeneise findLastIndex with Array for refinement

**Before submitting a pull request,** please make sure the following is done:

- Fork [the repository](https://github.com/gcanti/fp-ts) and create your branch from `master`.
- Run `npm install` in the repository root.
- If you've fixed a bug or added code that should be tested, add tests!
- Ensure the test suite passes (`npm test`).

**Note**. If you find a typo in the **documentation**, make sure to modify the corresponding source (docs are generated).

### CODE REVIEW

**Comment by gcanti** [comment]
@sledorze I'm wondering, is there a reason you implemented them as static functions instead of methods?

**Comment by sledorze** [comment]
@gcanti no particular reasons beside I'm a bit on the staticLand side.
I can change it, it will be better for API discovery.
May we expose both?

**Comment by gcanti** [comment]
> I can change it, it will be better for API discovery

:+1:

> May we expose both?

mhh, I'm not a fan of having two ways of doing the same thing

**Comment by gcanti** [comment]
@sledorze I'm ok with upgrading tslint to latest

**Comment by sledorze** [comment]
@gcanti looks like the CI failing because there's no npm

**Comment by sledorze** [comment]
@gcanti awesome docs checks 👍

**Comment by sledorze** [comment]
@giogonzo are your concerns about not supporting all lock files formats? or generally using any lock file system?

**Comment by sledorze** [comment]
@giogonzo maybe that's something to discuss in a new fresh issue. (and I'm expecting that one to be closed very soon :) )

**Comment by giogonzo** [comment]
@sledorze @gcanti sure, definitely out of scope. I'm just interested in understanding the rationale behind versioning a lock file in a library repository (any file format, same reasoning applies to yarn.lock and package-lock.json IMO).

Suppose that `io-ts` has in incompatibility with a newly released `fp-ts` patch or minor release (I know this shouldn't happen in a semver-compliant world.. but it happens from time to time). if `io-ts` has a committed package-lock file (or yarn lock), the author will not be aware of this issue untile the lock file is updated. A user of `io-ts` creating a new app instead, will get the latest versions for both `fp-ts` and `io-ts` -> broken app. Due to this scenario, I find simpler to just avoid committing lock files to library repos.

**Pull request merged**
